DROP TABLE if exists messages;
DROP TABLE if exists items;
DROP TABLE if exists users_authorities;
DROP TABLE if exists users;
DROP TABLE if exists products_state;
DROP TABLE if exists products_des_image_urls;
DROP TABLE if exists products;

CREATE TABLE `users` (
	`USER_ID` bigint(10) NOT NULL AUTO_INCREMENT,
	`NAME` CHAR(50) NOT NULL,
	`NAME_CRC` INT NOT NULL,
	`EMAIL` CHAR(50) NOT NULL,
	`EMAIL_CRC` INT(11) NOT NULL,
	`PASSWORD` VARCHAR(100) NOT NULL,
	`TELEPHONE` CHAR(50) NOT NULL,
	PRIMARY KEY (`USER_ID`),
	INDEX `EMAIL_CRC` (`EMAIL_CRC`),
	INDEX `NAME_CRC` (`NAME_CRC`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `users_authorities` (
	`USER_ID` bigint(10) NOT NULL,
	`AUTHORITY` CHAR(50) NOT NULL,
	CONSTRAINT `FK__users` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `products` (
  `PRODUCT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(11) NOT NULL,
  `CAR_MAKER_NO` int(11) DEFAULT NULL,
  `CAR_TYPE_NO` int(11) DEFAULT NULL,
  `CAR_MODEL_NO` int(11) DEFAULT NULL,
  `CAR_YEAR` int(11) DEFAULT NULL,
  `MAIN_CATEGORY_NO` int(11) DEFAULT NULL,
  `SUB_CATEGORY_NO` int(11) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `PRICE` double DEFAULT NULL,
  `QUANTITY` int(11) DEFAULT NULL,
  `LIST_IMAGE_URL` char(100) DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `products_des_image_urls` (
	`PRODUCT_ID` BIGINT(20) NULL DEFAULT NULL,
	`NORMAL_URL` CHAR(100) NULL DEFAULT NULL,
	`ZOOMIN_URL` CHAR(100) NULL DEFAULT NULL,
	INDEX `FK_products_des_image_urls_products` (`PRODUCT_ID`),
	CONSTRAINT `FK_products_des_image_urls_products` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `products_state` (
	`PRODUCT_ID` BIGINT(20) NOT NULL,
	`STATE` VARCHAR(255) NULL DEFAULT NULL,
	INDEX `FK_products_state_products` (`PRODUCT_ID`),
	CONSTRAINT `FK_products_state_products` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `items` (
  `ITEM_ID` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(11) NOT NULL,
  `PRODUCT_ID` bigint(20) DEFAULT NULL,
  `QUANTITY` int(11) NOT NULL,
  PRIMARY KEY (`ITEM_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `PRODUCT_ID` (`PRODUCT_ID`),
  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `items_ibfk_2` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `products` (`PRODUCT_ID`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `messages` (
	`MESSAGE_ID` INT(10) NOT NULL AUTO_INCREMENT,
	`TO_USER_ID` bigint(10) NOT NULL,
	`FROM_USER_ID` bigint(11) NOT NULL,
	`CONTENT` VARCHAR(255) NOT NULL,
	`SENDING_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX `FK_messages_users` (`TO_USER_ID`),
	PRIMARY KEY (`MESSAGE_ID`),
	CONSTRAINT `FK_messages_users` FOREIGN KEY (`TO_USER_ID`) REFERENCES `users` (`USER_ID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

