DROP TABLE if exists users;

CREATE TABLE users (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	TELEPHONE VARCHAR(15) NOT NULL,
	PRIMARY KEY (ID),
	INDEX(EMAIL, PASSWORD)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

DROP TABLE if exists parts;

CREATE TABLE parts (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
    MIDDLE_CATEGORY INT NOT NULL, 
    LARGE_CATEGORY INT NOT NULL, 
    KEYWORD1 VARCHAR(20), 
    KEYWORD2 VARCHAR(20), 
    KEYWORD3 VARCHAR(20), 
    KEYWORD4 VARCHAR(20), 
    KEYWORD5 VARCHAR(20),
    PRICE BIGINT NOT NULL,
    MAKER VARCHAR(50) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    QUANTITY INT NOT NULL,
    IMAGE_URL1 VARCHAR(100),
    IMAGE_URL2 VARCHAR(100),
    IMAGE_URL3 VARCHAR(100),
    IMAGE_URL4 VARCHAR(100),
    DESCRIPTION VARCHAR(1000),
    REGION INT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
        